### ISSUE TITLE
OMEROService context missing

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/ImageJPlugins#3]
I updated the POM of the project to use pom-imagej 16.4.0 as a parent.
Now when I tried to test my op / command I receive this:

java.lang.IllegalArgumentException: Required service is missing: net.imagej.omero.OMEROService
Context: org.scijava.Context @ 3e9803c2
ClassLoader: sun.misc.Launcher$AppClassLoader@4e0e2f2a

I'm trying to run this [code](https://github.com/OmegaProject/ImageJPlugins/blob/master/OMEROImageImporter/src/main/java/imagej2_omegaPlugins/omeroImageImporter/OmeroImageReader.java).

If I downgrade to pom-imagej 11.0.0 the [original command](https://github.com/OmegaProject/ImageJPlugins/blob/master/OMEROImageImporter/src/main/java/imagej2_omegaPlugins/omeroImageImporter/OmeroImageBrowser.java) I made is correctly launched by imagej.

Do you have any suggestion about this @ctrueden?

**Comment by Akramhar** [comment]
If I downgrade to pom-imagej 11.0.0 the [original command] (https://github.com/OmegaProject/ImageJPlugins/blob/master/OMEROImageImporter/src/main/java/imagej2_omegaPlugins/omeroImageImporter/OmeroImageBrowser.java) I made is correctly launched by imagej.

**Comment by Akramhar** [comment]
I moved version using pom-imagej 16.4.0 in [here](https://github.com/OmegaProject/ImageJPlugins/tree/master/OMEROImageBrowserNew) while the working version using pom-imagej 11.0.0 is [here](https://github.com/OmegaProject/ImageJPlugins/tree/master/OMEROImageBrowser).

I discovered that the problem is because most of the contexts don't get created anymore during the imagej init, while in the previous version there was a uber context.
~~I'm trying to understand how to create the OMEROService in the plugin atm.~~ not needed anymore because of Curtis answer below

**Comment by ctrueden** [comment]
The issue is that `OMEROService` extends `Service` directly, without implementing any marker interfaces (e.g., `ImageJService`) which would result in it getting included by default when you create a new gateway (e.g., `net.imagej.ImageJ`) from scratch.

We should probably change `OMEROService` to extend `ImageJService`.

In the meantime, you can avoid the issue by writing:

``` java
Context context = new Context();
ImageJ ij = new ImageJ(context);
```

This will initialize _all_ services, regardless of which layer they are part of.

**Comment by Akramhar** [comment]
Thanks @ctrueden this will solve the issue at least for my debugging :)

**Comment by ctrueden** [comment]
Finally fixed this on the ImageJ-OMERO side. Although the fix is not yet released, of course.
